### ISSUE TITLE
Add close and show events back

### ISSUE THREAD

**Issue by annevk** [whatwg/notifications#100]
They were not removed from implementations as discovered in https://github.com/w3c/web-platform-tests/pull/5188.

Related Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=437286.

This means reverting f2e3cad125ca7c7204889c214b392e3312fc5f74 and 53ebcf25458f7581570a228cfa11ad7cb27ff4ea.

cc @foolip @beverloo

**Comment by beverloo** [comment]
I'm +1 on adding them back. While @foolip pointed out that the metrics we've recorded are not representative, I'm aware of various larger sites (Gmail, Calendar) that rely on these. Continuing to support them is trivial for us.

**Comment by anitawoodruff** [comment]
+1 for this! :)
