### ISSUE TITLE
Small error in the "create a notification" algorithm

### ISSUE THREAD

**Issue by hzr** [whatwg/notifications#101]
The [create a notification](https://notifications.spec.whatwg.org/#create-a-notification) algorithm, step 7 says

> Set _notification_’s title to _options_’s `title`.

I think this should say:

> Set _notification_’s title to `title`.

(_title_ is not used elsewhere in the algorithm, and [NotificationOptions](https://notifications.spec.whatwg.org/#dictdef-notificationoptions) doesn’t have a title.)

**Comment by annevk** [comment]
Thanks!
