### ISSUE TITLE
Unsubscribe Callback

### ISSUE THREAD

**Issue by themar** [whatwg/notifications#112]
Hi, 
I think it will be great if there a callback event for unsubscribe. So once use block notification access new event listener fired on service worker to inform the backend about user unsubscribe. This will give web push notification more power and It will be easy for publisher to track subscribers behaviors 
Thanks.

**Comment by beverloo** [comment]
Hi - your question is appropriate for the Push API:
https://github.com/w3c/push-api
https://w3c.github.io/push-api/

To answer it: you'll be able to listen to the `pushsubscriptionchange` event in your Service Worker that will inform you of such changes. Only Firefox has a (partial) implementation right now.
