### ISSUE TITLE
getNotifications manipulates ES arrays in parallel steps

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/notifications#113]
https://notifications.spec.whatwg.org/#dom-serviceworkerregistration-getnotifications is manipulating and ES array in parallel steps.  It says things like "push that object to objects".  How is that supposed to work?  Is that using `Array.prototype.push`?  If so, is it using the initial value of that?  Even if it does, that can be affected by accessor properties on `Array.prototype` and in particular can run arbitrary script, which is not OK in parallel.

**Comment by annevk** [comment]
It also doesn't queue a step to resolve the promise... (Although promises in general are underdefined I suppose.)

I think what this should do instead is to just build up a list and resolve the promise with that and let the IDL layer take care of converting the list to a new `Array`.

**Comment by annevk** [comment]
Using https://infra.spec.whatwg.org/ terminology to make such a list this should be relatively straightforward.
