### ISSUE TITLE
Optional non-persistent Notifications and feature detection

### ISSUE THREAD

**Issue by akihikodaki** [whatwg/notifications#116]
# Summary
Chromium on Android (and possibly other embedders) does not support non-persistent Notifications, but there is no straightforward way to detect such lack of the feature. It is nice to have a standardized solution.

# Details
Chromium "allows the embedder to disable the Notification constructor."
https://codereview.chromium.org/901843006

And the Notification JavaScript constructor id disabled for Android with that facility.
https://codereview.chromium.org/920153002

It removes non-persistent notification support.

An article concerning that says from Google:
> The best way to feature detect for Android and desktop at the moment is to do the following:
>
> ```JavaScript
>function isNewNotificationSupported() {
>    if (!window.Notification || !Notification.requestPermission)
>        return false;
>    if (Notification.permission == 'granted')
>        throw new Error('You must only call this \*before\* calling Notification.requestPermission(), otherwise this feature detect would bug the user with an actual notification!');
>    try {
>        new Notification('');
>    } catch (e) {
>        if (e.name == 'TypeError')
>            return false;
>    }
>    return true;
>}
>
> ```

https://developers.google.com/web/updates/2015/05/notifying-you-of-changes-to-notifications#android_notifications

It says "You must only call this *before* calling Notification.requestPermission(), otherwise this feature detect would bug the user with an actual notification!", but the user agent may remember the decision in a previous session, and therefore, to feature detect, we have to use localStorage or other persistent storages. That is troublesome and inefficient.

Moreover, the Notification constructor is not optional, and there is no assurance that the feature detection may not break.

**Comment by annevk** [comment]
I don't understand how this is even good feature detection, wouldn't this create a notification in implementations that do support non-persistent notifications?

**Comment by annevk** [comment]
I guess you could do `new Notification('', { data: Symbol() }` and see if that throws a `TypeError` or "DataCloneError" `DOMException`, but even that doesn't seem foolproof against implementations that do not support `data`.
