### ISSUE TITLE
Temporary disabled notifications

### ISSUE THREAD

**Issue by NtFreX** [whatwg/notifications#129]
Hey together

I don't know if this is the correct place for my question but I will ask it anyway.

According to [this site](https://notifications.spec.whatwg.org/#permission-model) there are three permission states: `default`, `denied` and `granted`. In Firefox the user can disabled notifications temporary and I would like to persent that state to the user. So basicly I want to differentiate between `denied` and something like `temporary_denied`.

How could this be achieved? Through a browser specific feature? Or even through change in the standard? Or anything else?

EDIT: [Cross reference to stackoverflow](https://stackoverflow.com/questions/49490817/check-if-browser-notifications-are-temporary-disabled-in-firefox)

**Comment by annevk** [comment]
I somewhat doubt Firefox would want to expose that difference to web developers. If they do, then it's possible this could be exposed through a change in the API.

**Comment by NtFreX** [comment]
@annevk Thanks for your quick answer. The only reason why I need that state is to show the user how he can activate the notifications again. When they are denied the user has to change the settings. When they are temporary denied the user has to open a new tab/window. Do you know where would be the best place to ask Firefox if the want to expose that information^^?

**Comment by annevk** [comment]
Let's see if @jan-ivar has any feedback. If that doesn't work out, you could file a bug over at https://bugzilla.mozilla.org/enter_bug.cgi?product=Core.

**Comment by jan-ivar** [comment]
@NtFreX I put up an answer to your specific question on stackoverflow. Hope that helps.

> I need that state is to show the user how he can activate the notifications again

`temporary_denied` is just `default` in response to a request. When is that insufficient?

FYI users can clear both temporary and permanent blocks the same way in Firefox (the ⓧ):

![screenshot](https://screenshotscdn.firefoxusercontent.com/images/3226a3e7-b787-4231-b9db-89378f797c00.png)

**Comment by NtFreX** [comment]
@jan-ivar Thanks for your answer. I'll just persist if I asked the user already as suggested in your SO answer.
