### ISSUE TITLE
A new popup ad

### ISSUE THREAD

**Issue by ashegoulding** [whatwg/notifications#140]
Hi

I just wanted to say thank you for making a new type of popup ad that nobody wanted. I'll always appreciate the new feature on our browsers that everyone wants to disable. I also thank you for implementing the option to disable the feature. No one else could've done it that fast.

I support your effort to make the internet a better place by solving non-existent problems.

Regards

...

I get it. I can't say it's bad. It's always good to see web browsers having the concepts that only native apps had. Even if it wasn't for notifications, there'll always be a way round to implementing intrusive ads/contents. The thing is that HTML5 notifications made it easy and universal. Now that every site I visit asks for it, it seems to me that rolling out with the option enabled by default was a mistake.

I'm making a lot of assumptions, but I think that there'll come a time when notifications are blocked the same way the `window.open()` function is blocked. More and more sites will bodge the API and people will get used to clicking that block button. And when that time comes, someone's gonna feel sorry for this.

**Comment by annevk** [comment]
I think you're correct that there's more work to be done on the UX side of things (in particular around push notifications, which are mostly what sites ask for, not the basic notifications defined here), and I believe that to some extent that's happening in the respective browser teams.
