### ISSUE TITLE
No Longer Working on Edge or Chrome

### ISSUE THREAD

**Issue by wilecoyte78** [whatwg/notifications#144]
This is no longer working on Chrome or Edge it only works on Firfox:

https://codepen.io/jeezzemax/pen/LJcgx?editors=1010

**Comment by beverloo** [comment]
Hi @wilecoyte78, thank you for the issue.

In this example the top-level origin is `codepen.io`, but the permission request for showing the notification is being triggered from `s.codepen.io`—the iframe from which the example is being run. Chrome and Edge disallow requesting permission from an iframe, which breaks this example. A message is displayed in the DevTools console when using Chrome.

I don't think this is a spec issue as it relates to UA-specific permission behaviour, so let me go ahead and close this. Feel free to file a bug on the Chrome and/or Edge bug trackers if you feel you have a reason that this should be reconsidered.

**Comment by wilecoyte78** [comment]
What about this one https://tests.peter.sh/notification-generator/ It only works in firefox as well.
