### ISSUE TITLE
Consider using DOMHighResTimestamp instead of DOMTimeStamp

### ISSUE THREAD

**Issue by yoavweiss** [whatwg/notifications#171]
We're considering our options RE `DOMTimeStamp`, and wondering what it's used for. It seems less well-defined than `DOMHighResTimestamp`. Would y'all consider switching over?

See heycam/webidl#2 for discussion.

**Comment by annevk** [comment]
It's not clear to me that's feasible as someone might currently feed this value into a `Date` or some such and that would completely break if the value was suddenly relative to a different time origin.

**Comment by yoavweiss** [comment]
I wonder if Someone™ can get stats about how often that actually happens.

^^ @beverloo

**Comment by beverloo** [comment]
We see timestamps being used quite intensively for notifications, particularly for communication-related use cases, but to my knowledge we don't have the right infrastructure to measure, at scale, where the value comes from or where it goes next.

The Notifications API defines it as:
> a DOMTimeStamp representing the time, in milliseconds since 00:00:00 UTC on 1 January 1970

That matches the time origin used by `Date`, doesn't it? What I'm not clear on would be the effective difference between the current `unsigned long long` (`DOMTimeStamp`) and the `double` (`DOMHighResTimestamp`)

**Comment by yoavweiss** [comment]
The main difference is that DOMHighResTimestamp is relative to the `timeOrigin` and not to the epoch, so developers would start getting different values than the ones they are used to.

**Comment by beverloo** [comment]
We won't be able to adopt that. While we don't have decisive metrics, I manually checked 10 of the larger notification users and 7 included a `timestamp` relative to the epoch, which already pushes us well into double digit usage percentages.

**Comment by yoavweiss** [comment]
Makes sense :/
