### ISSUE TITLE
Add date/timestamp field

### ISSUE THREAD

**Issue by annevk** [whatwg/notifications#20]
See http://lists.w3.org/Archives/Public/public-whatwg-archive/2014Aug/0017.html

@sicking, I guess this should just mimic the timestamp used for Date objects? Do we expect applications to worry about timezones?

**Comment by sicking** [comment]
Ping? Any reason not to do this? This seems like a simple feature to add, and notifications look really ugly when you get a notification which says "Meeting starting in 10 minutes [8 minutes ago]" where the part inside the [] is rendered by the platform in a different color.

**Comment by annevk** [comment]
I guess we should do this, yes. Perhaps @beverloo or @johnmellor wants to create another PR?

**Comment by beverloo** [comment]
I'm in favor of doing this too, and will prepare a PR tomorrow. Thanks for kicking this up, @sicking! :)
