### ISSUE TITLE
Suggestion to Add Translated Link for notifications (Simplified Chinese 简体中文)

### ISSUE THREAD

**Issue by JinDX** [whatwg/notifications#221]
### What is the issue with the Notifications API Standard?

I have completed the translation of the notifications specification into Simplified Chinese (简体中文). Here is the link to the translated document:

- [Translated version of the specification in Simplified Chinese](https://htmlspecs.com/notifications)

It would be helpful for international users if this link could be added to the official documentation or the README.

Thank you for considering this request!

**Comment by annevk** [comment]
@zqzhang given that https://github.com/w3c-html-ig-zh/notifications is 9 years old now I'm going to replace the link to that translation with this newer one by @JinDX.

Thank you @JinDX!
