### ISSUE TITLE
Consider badges

### ISSUE THREAD

**Issue by annevk** [whatwg/notifications#23]
See http://discourse.specifiction.org/t/native-numerical-notifications/566 for the rough idea.

**Comment by domenic** [comment]
Pointer to that discussion?

**Comment by annevk** [comment]
https://lists.w3.org/Archives/Public/public-whatwg-archive/2014Aug/0211.html
https://lists.w3.org/Archives/Public/public-whatwg-archive/2014Sep/0008.html
