### ISSUE TITLE
Not being able to construct a Notification object in SW conflicts with NotificationEventInit

### ISSUE THREAD

**Issue by beverloo** [whatwg/notifications#25]
Step 2 of the constructor algorithm notes:
    "If entry settings object's global object is a ServiceWorkerGlobalScope object, throw a TypeError exception."

Creating a NotificationEvent uses the NotificationEventInit dictionary, which has a required attribute of type Notification.

How would one actually give this attribute a value?

+@johnmellor

**Comment by annevk** [comment]
I think it's fine that this doesn't work great personally.
