### ISSUE TITLE
Notification close event for a notification

### ISSUE THREAD

**Issue by gauntface** [whatwg/notifications#31]
At some point there was a close event proposed for Notifications (https://developer.mozilla.org/en-US/docs/Web/API/Notification/onclose) which no longer seems to be in the spec.

It would be useful to have this event for stats and ultimately shaping when developers send notifications (you can imagine a scenario of realizing that send push messages on specific categories are always closed by the user so the site reduces the number of pushes for that category).

Is there a reason this isn't supported by the spec?

**Comment by annevk** [comment]
Judging from https://github.com/whatwg/notifications/commit/53ebcf25458f7581570a228cfa11ad7cb27ff4ea I suspect the October 2014 archives and perhaps the month prior of the WHATWG mailing list have definitive answers.

The main reason it's no longer there is that non-service worker notifications are no longer persistent and disappear after a few seconds. And for service worker notifications the use cases were not compelling enough.

**Comment by marco-c** [comment]
It could be useful to gather statistics about the notifications. For example, I might want to know if the push notifications I'm sending are effective or not (I can count the number of notifications clicked and the number of notifications ignored, but I can't count the number of notifications closed).

**Comment by annevk** [comment]
@marco-c see #61, we're considering adding this back for persistent notifications.
