### ISSUE TITLE
Reflecting renotify, silent, noscreen and sticky on the Notification interface.

### ISSUE THREAD

**Issue by beverloo** [whatwg/notifications#32]
The NotificationOptions dictionary contains four keys which aren't being reflected on Notification objects: renotify, silent, noscreen and sticky.

What's the reason for not adding them? While I don't foresee any major use-cases, it allows for feature detection and manual cloning of notifications. Implementation cost is near zero for us.

Happy to write a PR.

**Comment by annevk** [comment]
I think I simply forgot. Might have looked at vibrate for inspiration and that is not reflected at the moment due to some IDL complexity with arrays.

**Comment by annevk** [comment]
This got fixed by #33.
