### ISSUE TITLE
Notification.hasPermission resolving with denied but setting Notification.permission to default

### ISSUE THREAD

**Issue by owencm** [whatwg/notifications#35]
Just a minor thought:

It feels strange to me that in Chrome, dismissing the permission infobar for Notifications resolves the promise with 'denied', but Notification.permission is set to 'default'.

I can still write the code I want, and maybe this is the best option, but the semantics definitely feel strange since I didn't 'deny' the request, I simply 'deferred' it.

I don't know what the solution is here, but I wonder if 'deferring' or 'ignoring' a permission request is a common enough pattern that UAs may wish to implement that it should be first class in the API. 

Ho hum.

**Comment by annevk** [comment]
Well, that behavior of Chrome might be a bug as that is definitely not part of the specification...

**Comment by beverloo** [comment]
Agreed. The specification does not describe this behavior, so please file such issues against Chrome.

In this case, see https://crbug.com/434547.
