### ISSUE TITLE
Notification.get() partial exposure

### ISSUE THREAD

**Issue by beverloo** [whatwg/notifications#37]
https://notifications.spec.whatwg.org/#service-worker-api

Any context which has access to a ServiceWorkerRegistration object can display persistent notifications, which includes Documents. However, only Service Workers can access the list of existing notifications.

What about having ServiceWorkerRegistration.getNotifications(...) instead?

**Comment by annevk** [comment]
What's wrong with `[Exposed=ServiceWorker]`? I rather like that pattern.

**Comment by beverloo** [comment]
Exactly what I said in my first paragraph - document can show notifications, but can't get notifications, whereas Service Workers can do both. I'd like any context that can get a SWR to do either.

**Comment by annevk** [comment]
I read that paragraph as a statement of fact, not as a problem statement :-) I like your proposal.

**Comment by beverloo** [comment]
I'll take that as a "PRs welcome" hint and will send you one today :-).

**Comment by annevk** [comment]
I'm on it, no worries.

**Comment by foolip** [comment]
Many years later I see that Firefox still has `Notification.get()`, and I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1689565. @annevk maybe a historical test for this would be good too?
