### ISSUE TITLE
Notification.data should be replaced by Notification.id or specify very clear data size limit

### ISSUE THREAD

**Issue by mounirlamouri** [whatwg/notifications#39]
Notification.data is yet another storage mechanism on the platform which is a bit sad to see. We could easily imagine that Notifications have an id that could be used to store data associated to them instead.

The only issue with that would be that the Notifications could be closed in which casee the applications might have stored data worth cleaning up but could forget about it. Given that they can read the currently open notifications, it is definitely something applications can handle but we can imagine some will do it wrong. Though, if they do it wrong, they only harm themselves by increasing their disk usage.

Having arbitrary data on Notifications can be scary because it adds new form of storage that isn't clearly related to the page lifecycle which might lead to scary bugs (data leaking).
It will also increase the general complexity of the platform with regards to data. Things like quota will have to take into account Notification.data to prevent this to be abused.
It will also increase implementation complexity significantly: storing an ID on the notification is probably supported by most platforms, raw and arbitrary data isn't AFAIK.

An alternative to killing Notification.data would be to restrict the size of what can be stored in them. We want that to be interoperable so that size limitation should be specfied.

**Comment by annevk** [comment]
We just recently went over this in #38 and that was not the first time either. I don't think either suggestion makes much sense.

**Comment by beverloo** [comment]
I strongly disagree with dropping Notification.data, even when adding a Notification.id. While I can see this being _cleaner_, it implies putting a requirement on the developer to use an IndexedDB for even the simplest Notification flows.

We've already had feedback that developers are using either the `tag` or the hash part of the `icon URL` to store small bits of data. @PaulKinlan @Gauntface

The fact that the data associated with a notification is tied to the lifetime of the notification is a benefit in many cases. It makes Notification.data as a data storage highly unreliable and inconvenient for any other kind of information.

As for added complexity, we (Chrome) need to implement a database for other reasons anyway. Adding `data` on top of this is not a high cost. The infrastructure for storing arbitrary data is already in place. (See `SerializedScriptValue`.)

In #38 I argued for an upper limit to prevent abuse. I still think we need something like that for implementation sanity reasons, but I'm fine with that being a high UA-specific limit.

**Comment by gauntface** [comment]
+1 @beverloo's comments.

Currently not having data is frustrating and switching for id will likely lead to just using a string of serialized JSON in the majority of cases.

An upper bound on data seems like a good path and I think most developers would not be that surprised if they started to receive errors when adding a huge object to notification data - although I would expect many to hit this issue.

These comments obviously ignore the implementation complexity and only take into account the API layer.

**Comment by annevk** [comment]
I assume you meant that you would *not* expect many developers to hit a browser-defined limit?

**Comment by gauntface** [comment]
Yes - apologies, I've amended my comment.
