### ISSUE TITLE
Supporting notification.vibrate attribute in spec

### ISSUE THREAD

**Issue by SH919Park** [whatwg/notifications#43]
The specification currently defines the "vibrate" option in the NotificationOptions dictionary, but doesn't expose the attribute because of the following bug:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=23682

Because of this, developers cannot feature detect whether vibration is available, and won't be able to clone or serialize notifications that use vibration either. This is inconsistent with all other attributes of the Notification object.

For fixing this issue, I think that we should continue the discussion in Bug 23682, and update the Notification API when an appropriate solution has been found there.

Blink is ready to ship support for vibrate options. and we support the vibrate attribute for testing purposes, but do not plan to ship it at this time

Blink implementation is as following:
[WebIDL]
readonly attribute sequence&lt;unsigned long&gt;? vibrate;

To give a few examples:
1. new Notification('Title', {}).vibrate returns "null"
2. new Notification('Title',  { vibrate: 10 }).vibrate returns "[10]"
3. new Notification('Title',  { vibrate: [10, 0] }).vibrate returns "[10]"
    - In this case, vibrate pattern is sanitized.
4. new Notification('Title',  { vibrate: [10, 20, 30] }).vibrate returns "[10, 20, 30]"

All returned arrays will be new objects.

Thanks
Sanghyun Park

**Comment by annevk** [comment]
Can't we simply use an empty array rather than null? I prefer not switching the type if there's not a good reason. I agree that IDL is the main blocker here.

**Comment by SH919Park** [comment]
The reason for the return value to Null is in order to check whether vibrate is set or not.
BTW, as your said, it seems to be better to return empty array.

@beverloo 
What do you think about this?

**Comment by foolip** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=23682 has been fixed now so it should be possible to expose Notification.vibrate as `FrozenArray<unsigned long>`.

**Comment by annevk** [comment]
See https://github.com/plinss/widlparser/issues/8 for why this is taking a little longer.

**Comment by annevk** [comment]
@SH919Park do you want your Korean name listed in the acknowledgments section as well?

**Comment by SH919Park** [comment]
@annevk  I'd appreciate it if you would add it like the following: 박상현(Sanghyun Park)

**Comment by annevk** [comment]
Done (with a space before "(" for consistency with other specifications).

**Comment by SH919Park** [comment]
Thanks :)
