### ISSUE TITLE
Add optional action buttons to notifications

### ISSUE THREAD

**Issue by johnmellor** [whatwg/notifications#44]
[Android 4.1+][1], [iOS 8+][2], [Chrome Apps][3] and [Mozilla XUL][4] all support showing action buttons at the bottom of a notification. This allows users to quickly handle the most common tasks for a particular notification, without having to open the originating application.

[1]: http://developer.android.com/design/patterns/notifications.html#actions
[2]: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIUserNotificationAction_class/
[3]: https://developer.chrome.com/apps/notifications#property-NotificationOptions-buttons
[4]: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Method/appendNotification

We'd like to add action buttons to the Notifications API, and implement them in Chrome.

Strawman API:
```webidl
dictionary NotificationAction {
    DOMString id;  // If clicked, this will become NotificationEvent.actionId
    DOMString title;  // Button text
}
partial dictionary NotificationOptions {
    sequence<NotificationAction> actions;
}
partial interface Notification {
    FrozenArray<NotificationAction> actions;
}
partial interface NotificationEvent {
    DOMString actionId;  // Id of clicked action, or null if user clicked notification body instead
}
```

Action support would be feature detected via `Notification.prototype.hasOwnProperty('actions')`. UAs which expose that must support up to 2 actions. If more than 2 actions are provided in `NotificationOptions.actions`, throw a TypeError. The number 2 was chosen because it's the maximum supported by iOS and Chrome OS, and although Android supports 3 buttons, Chrome for Android already uses one of the available slots to show a link to per-origin settings. (If later UAs want to support more actions, we could add a `maxSupportedActions` constant to Notification).

Presentation of actions would be implementation-defined, for example on Android action buttons are only shown when the notification is [expanded](http://developer.android.com/design/patterns/notifications.html#ExpandedLayouts). Hence websites should not rely on actions, and should provide the same functionality via alternate UI that can be reached by clicking on the notification body.

I explicitly left out action icons, since only Android supports them, and Android currently only supports icon resources shipped in a native app's apk (not icons downloaded at runtime), so they wouldn't be implementable yet there either.

@sicking @beverloo

**Comment by owencm** [comment]
+1. 

One extremely minor miscellaneous thought that comes to mind: `id` sounds like it will be generated for me whereas the label `tag` sounds like I will be providing it.

**Comment by sicking** [comment]
Yup, I'm definitely in support of buttons. API looks good though I'd like to support an icon in addition to the text. I'm also fine with `tag` rather than `id`.

**Comment by sicking** [comment]
I also think that having a `maxSupportedActions` property somewhere sounds like a good idea.

**Comment by beverloo** [comment]
@owencm `tag` would be duplicated with `Notification.tag`. I'd prefer to use a different term. `id` would work, but maybe we could just call it `action`?

@sicking Chrome on Android won't be able to support icons for the foreseeable future, unless we'd specify some kind of enumeration with predefined icons (which I'd really like to avoid). Chrome desktop is fine with icons. As far as I'm aware, however, Chrome desktop and Android are the only platforms where icons are supported today.

John also spoke of `maxSupportedActions` earlier. I'm OK with adding it.

**Comment by sicking** [comment]
Ah, bummer about icons. I agree we don't want to do an enumeration.

I'd still be interested in adding them where we can, as long as we make it very easy for developers to detect if they are supported.  So maybe have a property alongside `maxSupportedActions` like `actionsSupportIcons`. Even if that means they are just displayed on Chrome desktop and Firefox desktop for now.

Or we can wait to a later iteration.

**Comment by owencm** [comment]
@beverloo I'm fine with sticking to `id` if we feel `tag` would cause confusion.

I have a mild preference for keeping things simple and getting actions working as an MVP without icons and then add icons in a later iteration, unless there is an design that seems obvious and uncontroversial. Personally, I'm worried about there being details around what style icons should be provided, how UAs can mask them to change colors or match styles etc.

**Comment by sideshowbarker** [comment]
> Chrome desktop is fine with icons. As far as I'm aware, however, Chrome desktop and Android are the only platforms where icons are supported today.

Maybe I’m misunderstanding what you mean, but I know Firefox on OS X supports icons in web notifications specified through the `Notification.icon` property (constructor option). Or maybe you meant icons in some other context.

**Comment by beverloo** [comment]
@sideshowbarker Support for icons _on the buttons_. Normal icons are supported much more broadly :)

**Comment by johnmellor** [comment]
@sicking Another complication with action icons is that Android requires a white on transparent icon (even though in Lollipop+, these then get rendered as dark on light, using the alpha channel of the icon to [draw a solid color silhouette](https://code.google.com/p/chromium/issues/detail?id=460049#c11)). Unless all UAs agree to match that, we'd need to introduce some concept of alternate background colors. There's also a dependency on #28 and #5. So I'd lean towards adding icons in a later iteration.

@owencm @beverloo @sicking What about "name" instead of id/tag?

**Comment by annevk** [comment]
Is it easy to upgrade from a dictionary to a class-based object later on? Looks alright overall. It would expedite things if someone wrote up a PR.

**Comment by domenic** [comment]
I think it is a little unexpected from a developer point of view to have to supply { id, title } pairs, then do a switch statement in the notification event handler to figure out which was clicked. A more idiomatic JS API would be something like

```js
new Notification({
  ...
  actions: {
    "Mark as Read": function () { ... },
    "Archive": function () { ... },
    "Delete": function() { ... }
  }
});
```

I guess we can let people write author-friendly wrapper libraries for that though...

**Comment by beverloo** [comment]
That doesn't work for notifications which outlive the page they were created by, which, on mobile, will be the common case. Additionally, it doesn't give us the liberty to include icons in the syntax in a later iteration.

Given the constraints, I think the switch() statement is warranted.

**Comment by johnmellor** [comment]
An alternative to id/tag/name would be to simply expose an `actionIndex` property on `NotificationEvent`. Authors would then be able to index into `event.notification.actions`. However this could be tricky for authors who localize their button titles, hence the id/tag/name seems more robust.

(We could also call it `action` or `command` instead of id/tag/name).

**Comment by sicking** [comment]
You can always use a numeric id/tag/name if that makes your handling-code simpler. This works fine even though the platform takes a string since things like myArray["3"] works fine in JS.

**Comment by annevk** [comment]
`action` rather than `id`/`actionId` seems slightly preferable.
