### ISSUE TITLE
Make the BCP-47-validity requirement a document-conformance requirement rather than UA requirement

### ISSUE THREAD

**Issue by sideshowbarker** [whatwg/notifications#47]
This issue relates to issue #46.

To the degree that it makes sense to state document-conformance requirements for values provided in scripts (as opposed to provided in HTML markup), we should consider making BCP-47-validity for `lang` values a document-conformance requiring (aka authoring requirement) rather than a requirement that we place on UAs.

**Comment by aphillips** [comment]
For more information, see: https://lists.w3.org/Archives/Public/public-i18n-core/2015JulSep/0005.html
