### ISSUE TITLE
Add priority to notifications

### ISSUE THREAD

**Issue by johnmellor** [whatwg/notifications#49]
[Android 4.1+](http://developer.android.com/reference/android/app/Notification.html#priority), [Chrome Apps](https://developer.chrome.com/apps/notifications#property-NotificationOptions-priority) and [Mozilla XUL](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Method/appendNotification) all allow authors to specify a priority for each notification.

This has various possible use cases:
- It influences [notification ordering](http://developer.android.com/design/patterns/notifications.html#dialogs_and_toasts_are_for_feedback_not_notification);
- On Android, high priority notifications are initially shown as a [heads-up notification](http://developer.android.com/design/patterns/notifications.html) that overlaps the screen, before retreating to the notification shade;
- On desktop, it can be used as a hint to determine how long the notification should remain on screen - _this is based on frequent partner feedback that desktop users get annoyed by notifications cluttering their screens until manually dismissed_.

A complication here is that different platforms are likely to use different scales for priority. The most effective way to mitigate that seems to be to provide detailed (but non-normative) examples of what kinds of notifications are covered by each priority level, as in Android's [Correctly set and manage notification priority](http://developer.android.com/design/patterns/notifications.html#correctly_set_and_manage_notification_priority) documentation, in order to have a shared frame of reference.

As a strawman, I'd suggest that we standardize that same 5-point scale, with the same descriptions.

@sicking @beverloo

**Comment by sicking** [comment]
If we have numeric priorities, can we define the behavior of each priority level?

I'm not a big fan of having ambigious priorities that just is defined as "p1 is more important than p2". That makes it very hard for authors to know if what they have is a p3 or a p4 notification.

**Comment by johnmellor** [comment]
@sicking: that's why I suggested having clear descriptions (with examples) of each priority level. For example:

- "max": Urgent time-critical notifications, such as incoming calls and emergency alerts.

- "high": Important communications that should interrupt the user, such as emails and chats.

- "default": Ordinary notifications that should interrupt the user.

- "low": Notifications the user wishes to be informed about, but are less urgent, such as undirected social updates or available software updates.

- "min": Contextual or background information that should never interrupt the user, such as weather information or contextual location information.

**Comment by sicking** [comment]
Sounds good to me, but I think even documenting what we expect that implementations will do with these levels. I.e. what the UI will look like.

**Comment by johnmellor** [comment]
@sicking: that doesn't seem practical given the existing variations in notifications UX. Consider for example:
- Screen readers may have audio-only UI
- Notifications might be shown on connected smartwatches
- Some platforms have notification centers where a notification can remain without cluttering the screen, whereas on other platforms notifications overlap foreground windows until they are closed.
- Some OSes (like iOS) don't use priority levels, and instead rely on the user [manually sorting](http://www.imore.com/how-sort-and-organize-alerts-notification-center-iphone-and-ipad#manually-sort) their apps into priority order.

**Comment by sicking** [comment]
I definitely agree that we shouldn't mandate anything in the spec. However what we've seen time and again is that authors care about what UX users see. They don't care about semantic meanings. They are happy to use whatever semantics they need in order to get the UA to trigger the UX that they want.

But maybe it's better to do in documentation rather than specification...

**Comment by johnmellor** [comment]
Update: we addressed the "determine how long the notification should remain on screen" use case with `requireInteraction` in #53. The remaining use cases (notification ordering etc) are still useful, but seem less urgent to spec and implement.

**Comment by annevk** [comment]
Closing due to lack of continued interest.
