### ISSUE TITLE
Are notifications expected to remain on the user's screen on desktop?

### ISSUE THREAD

**Issue by beverloo** [whatwg/notifications#52]
Chrome currently keeps all notifications on the screen indefinitely (for desktop).

Most notifications can be moved to an off-screen notification center automatically. We've received feedback that some major players use setTimeout() in a Service Worker to automatically remove a notification from the user's screen after a number of seconds. This is a huge hack and only works because of Chrome's Service Worker-lifetime heuristics :/.

However, some notifications can't. Consider a calendar which may choose for a notification to remain on-screen until the event has finished. Other notifications that require the user to act may also prefer a more persistent display.

We'd like to start auto-closing them, as the vast majority of users and developers prefer this, but would like an option for developers to opt-in to keeping them on the screen if they deem this important.

What about an `autominimize` property, a boolean defaulting to `true`? The name certainly needs some bikeshedding. I'd prefer not to have the minimize-time specified by developers to avoid breaking user expectations.

+@sicking

**Comment by annevk** [comment]
If we're adding a feature it needs to default to false. `keepOnDisplay`/`requireInteraction`...

**Comment by beverloo** [comment]
I quite like `requireInteraction`.

Previously we considered overloading `priority` for this reason, but as Jonas pointed out, developers would start to assume behavior for the different priority levels. Being explicit about this seems better. I'd still love to hear some other opinions!

**Comment by sicking** [comment]
`requireInteraction` sounds good to me on desktop. But what does it do on mobile? It's probably fine to document that it does nothing.

**Comment by johnmellor** [comment]
Yes, most mobile OSes don't allow notifications to remain permanently onscreen (and it would be poor UX), so `requireInteraction` should be ignored there.

I tried to imply that by the "should" (and somewhat vague "readily available") on [line 74 of the PR](https://github.com/johnmellor/notifications/commit/e43ce6eaacbb376b77c1ed62b1c75e77c3dfc415#diff-ef412f25bf15f231f7a417d2d5fe6eb2R74). I'd be happy to make it more explicit; I'm just trying to avoid hardcoding UX decisions (and it's hard to define "mobile" as a boolean concept).
