### ISSUE TITLE
Add optional icon for NotificationAction

### ISSUE THREAD

**Issue by mvano** [whatwg/notifications#59]
On some platforms the button rendered for a NotificationAction can display an icon. [This example](http://arstechnica.com/gadgets/2014/06/android-wear-review/3/) shows it on an Android phone and watch.

I propose adding a simple icon attribute (like the one on [NotificationOptions](https://notifications.spec.whatwg.org/#dom-notificationoptions-icon)):
```
USVString icon;
```

**Comment by annevk** [comment]
This seems reasonable. I wonder if any other vendors have implemented this feature.

**Comment by johnmellor** [comment]
There are two subtleties here:

1. Authors may want to provide multiple resolutions/densities. But I think it's good to go ahead with a single URL string for now, then later on we can match whatever #5 and #28 decide to do for `NotificationOptions.icon` (presumably we'll either change both to be a union type, or extend the string parsing like srcset does).

2. The required foreground and background color of the icon are platform-specific (just on Android, KitKat and below show white on black icons, Lollipop and above show dark gray on light gray icons, and Android Wear shows white on blue icons). It's unreasonable to expect authors to provide different icons for every platform (or two icons at once for Lollipop+ phones connected to Android Wear), so instead I'd suggest specifying that the author SHOULD provide an image whose alpha channel can be used on its own as an alpha mask, such that UAs MAY ignore the color channels and generate the appropriate flat color icon(s) from the alpha mask.
For example some UAs would render the following icon:
[![colorful_settings_cog_checkerboard](https://cloud.githubusercontent.com/assets/563043/12455593/310c4a06-bf94-11e5-9ce4-599223c6c207.png)](https://cloud.githubusercontent.com/assets/563043/12455600/34771f7c-bf94-11e5-9c22-1ffe83987e50.png)
as:
![phone_notification](https://cloud.githubusercontent.com/assets/563043/12455585/2c8fc20a-bf94-11e5-849d-e3a504170481.png)

**Comment by mvano** [comment]
On 1 I agree that multiple image definitions can be done as a next step.

On 2 I am less keen, though it is a good point. While providing an easily masked icon is good advice for the current crop of popular platforms, I'd rather not include such a recommendation in the normative text. Perhaps it's more appropriate in a non-normative note.

**Comment by mvano** [comment]
>I wonder if any other vendors have implemented this feature.

It looks like for Windows 10 notification actions you can specify an imageUri in both [xml](http://blogs.msdn.com/b/tiles_and_toasts/archive/2015/07/02/adaptive-and-interactive-toast-notifications-for-windows-10.aspx) and [C#](https://code.msdn.microsoft.com/Toast-notifications-in-17c55610). In the screenshots, they seem to be white on transparent, but I couldn't find official guidance on size, style, or formats.

**Comment by mvano** [comment]
On iOS 8 actions for notifications were introduced, but I can't find great information about action icons there. There is this: in [this article](https://www.macstories.net/stories/ios-8-changed-how-i-work-on-my-iphone-and-ipad/) there's a section about notifications, and [this screenshot](https://313e5987718b346aaf83-f5e825270f29a84f7881423410384342.ssl.cf1.rackcdn.com/1410890745-2014-09-16-at-18-01-57-.jpeg) has a pause icon in it. It seems to be white on transparent, like for Android and Windows.

**Comment by beverloo** [comment]
@marco-c, would you have any input from Mozilla's POV?

**Comment by beaufortfrancois** [comment]
For info, Chrome Apps/Extensions notifications have an `iconUrl` for notification action buttons: https://developer.chrome.com/apps/notifications#type-NotificationOptions

**Comment by marco-c** [comment]
Not directly needed for the kind of things I'm currently building, but I can definitely see many use cases for this.
