### ISSUE TITLE
Unify notification creation API?

### ISSUE THREAD

**Issue by dandv** [whatwg/notifications#63]
The Notification() constructor and [ServiceWorkerRegistration.showNotification()](https://github.com/whatwg/notifications/issues/19#issuecomment-64197272) seem to have the same parameters. Would it make sense to expose Notification() to service workers?

See https://bugs.chromium.org/p/chromium/issues/detail?id=590029 for some more discussion.

**Comment by beverloo** [comment]
Justin and my comments on that issue explain why we don't want to do that— the lifetime of a Service Worker is deliberately undefined, which makes the on-instance events a bad fit.

I would recommend considering the current behaviour of the constructor to be deprecated. Is there a specific use-case you have in mind for which you think the constructor would be appropriate?

Personally I would like to see the constructor move closer to an [Android Toast](http://i.stack.imgur.com/EU8VY.png): simple, ephemeral and no fancy stuff beyond a `click` event. The [lifetime and UI integrations](https://notifications.spec.whatwg.org/#lifetime-and-ui-integrations) section of the specification explicitly allows for that, while disallowing them to do the same thing.

**Comment by annevk** [comment]
Welcome @dandv! I'm failing to see how it makes sense in service workers given that they require a very different event-based API from other environments.
