### ISSUE TITLE
Add small icon to Notification and NotificationOptions

### ISSUE THREAD

**Issue by mvano** [whatwg/notifications#65]
I'd like to split off the small icon discussion from issue #28 where it was first suggested for this specification, but it was not the main topic of that issue.

If it is provided a small icon may be used, if supported by the platform, to represent the notification when there is not enough space to display the notification itself. It may also be displayed inside the notification.

A site might use the same small icon for each notification, in that case it is simply a site identifier. Alternatively, different icons may be used by a site to distinguish types of notifications, like text messages and picture messages. Or, it could be used to express that there is only one piece of information vs multiple.

This concept exists on multiple platforms:

* For [Android notifications](http://developer.android.com/guide/topics/ui/notifiers/notifications.html) it is actually a required part of a notification, so that the notification can be represented in the status bar. There, user agents must fall back to a default icon when no small icon is provided by the site.
* It is used in the Windows lock screen on both [desktop](https://msdn.microsoft.com/en-us/library/windows/apps/hh779720.aspx) and [mobile](https://msdn.microsoft.com/en-us/library/windows/apps/jj207048(v=vs.105).aspx).
* There may be more? Please let me know!

In various contexts this icon may be referred to as "small icon", "app icon", or "notification badge". I suggest calling it "small icon" in general, and "smallIcon" in IDL:

``` webidl
dictionary NotificationOptions {
  USVString smallIcon;
};
interface Notification {
  readonly attribute USVString smallIcon;
};
```

I think this also raises the priority of committing to a solution for multiple image definitions as discussed in issue #28.

**Comment by beverloo** [comment]
I like `badge`.

**Comment by mvano** [comment]
It does have more meaning to it, and lacks camelCasing, ftw.

**Comment by mvano** [comment]
Alright, so the updated API would look like this:

``` webidl
dictionary NotificationOptions {
  USVString badge;
};

interface Notification {
  readonly attribute USVString badge;
};
```

@marco-c I'm looking for a bit more of Mozilla's perspective on this. Does this proposal sound ok?

**Comment by beverloo** [comment]
Focusing on Android a bit, it looks like Firefox is always using `R.drawable.ic_status_logo`, which is [the Firefox logo](https://github.com/mozilla/gecko-dev/blob/master/mobile/android/base/resources/drawable-xhdpi/ic_status_logo.png).

@mfinkle, perhaps you could comment on whether allowing the developer to specify their own icon instead is something you'd support? This is possible in Android M and beyond.

**Comment by mvano** [comment]
@annevk do you still want to block merging PR #67 on additional Mozilla feedback?

**Comment by marco-c** [comment]
> @marco-c I'm looking for a bit more of Mozilla's perspective on this. Does this proposal sound ok?

It makes sense to me, I like the `badge` name instead of `smallIcon`, which is less self-explanatory.

**Comment by mvano** [comment]
Thanks Marco!
