### ISSUE TITLE
Support Topic-Based PS-mapped notification subscriptions

### ISSUE THREAD

**Issue by RichardMaher** [whatwg/notifications#78]
Web Apps need to be able to compete with native apps by accessing de facto industry standard features: -

Google Cloud Messaging: -
https://developers.google.com/cloud-messaging/topic-messaging

Azure Notification Hubs: -
 https://blogs.windows.com/buildingapps/2013/09/16/delivering-push-notifications-to-millions-of-devices-with-windows-azure-notification-hubs/

**Comment by annevk** [comment]
Could you please elaborate? I don't really follow.

**Comment by beverloo** [comment]
Push message broadcasting is out of scope for this repository as well, so I'm closing this. Please limit these questions to the [push-api repository](https://github.com/w3c/push-api/issues).

**Comment by RichardMaher** [comment]
Well I have posted questions there previously that fell on deaf ears: -
https://github.com/w3c/push-api/issues/189 

@annevk I hope that provides some more detail about the requirement.

As with the XML vs HTML war, let me point out that W3C/IETF is once again barking up the wrong tree and wasting time that Web App developers can ill afford.

Either way I'm banned from W3C so I thought I spread the love.
