### ISSUE TITLE
Remove usage of "entry settings object"

### ISSUE THREAD

**Issue by annevk** [whatwg/notifications#86]
It seems most can be replaced with "relevant settings object" easily, but not entirely sure about usage in https://notifications.spec.whatwg.org/#create-a-notification.

**Comment by domenic** [comment]
Indeed, that particular usage will require tests for the `new Notification()` case. I am pretty sure Chrome and Firefox at least do not use entry based on code inspection/conversations with Boris, so we'll probably get lucky there.

**Comment by annevk** [comment]
@domenic I know you wrote tests for this for other APIs, do you have a pointer perhaps? Would be nice to get this resolved.

**Comment by annevk** [comment]
The HTML issue doesn't have any links, which I guess means we don't have any for the changes to `fetch()` and `XMLHttpRequest` either.

**Comment by domenic** [comment]
If you follow the links from the HTML issue you can end up at e.g. https://github.com/w3c/web-platform-tests/pull/3449

**Comment by domenic** [comment]
@annevk any interest in helping with tests for this? It looks pretty difficult as you need to set up origins where only one of them is granted permission, I guess.

I can also tell you from code inspection that Chrome does the relevant settings object (or current for statics) so maybe we should just change this without tests?

**Comment by annevk** [comment]
Yeah, I think that would be okay.
