### ISSUE TITLE
Define how resources are fetched

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/notifications#87]
At the moment this spec fetches a URL, but it should pass fetch a request. This should include the client of the request, whether it should be a CORS request etc etc.

**Comment by jakearchibald** [comment]
I'll create a PR

**Comment by jakearchibald** [comment]
Turns out there's an HTML comment pointing to https://www.w3.org/Bugs/Public/show_bug.cgi?id=24055 - I've created https://github.com/whatwg/notifications/pull/89 to make it clearer to people not looking at the source.

**Comment by annevk** [comment]
This is a duplicate of #5 by the way.
