### ISSUE TITLE
Race between showNotification & getNotifications

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/notifications#90]
```js
registration.showNotification('test', {
  icon: 'notification-icon.png'
}).then(() => registration.getNotifications()).then(notifications => {
  // ...
});
```

According to the current spec, it seems likely that the notification shown by `showNotification` won't be in the sequence returned by `getNotifications`.

`showNotification` resolves before fetching icons & running display steps, and the notification isn't added to the [list of notifications](https://notifications.spec.whatwg.org/#list-of-notifications) until after the display steps.

Possible solutions: `showNotification` should resolve later, once the notification is shown. Or, the notification should be added to the list of notifications sooner. Or, `getNotifications` should wait for pending notifications.

The first solution feels simplest.

**Comment by annevk** [comment]
That sounds reasonable. I'm not even sure why we resolve early. @beverloo?

**Comment by beverloo** [comment]
We actually implement that part of the spec incorrectly then - Chrome resolves once the notification has been shown. Waiting therefore SGTM.
