### ISSUE TITLE
Restrict the Notifications API to secure contexts

### ISSUE THREAD

**Issue by dominickng** [whatwg/notifications#93]
Chromium is moving to [restrict access to the notifications API over insecure contexts](https://groups.google.com/a/chromium.org/forum/#!topic/Blink-dev/IVgkxkRNtMo). There will be a deprecation warning in M58, scheduled for April 2017, with full removal in M60, scheduled for August 2017. The proposed behaviour is that calls to Notification.requestPermission() and the Notification constructor from an insecure context will act as though the user has denied permission (similar to the behaviour of the geolocation API from an insecure context).

Motivations for the restriction are as follows:

 * The notification permission acceptance rate for HTTPS sites is 3x greater than for HTTP sites in Chrome
 * Over 90% of daily notification permission requests in Chrome are already made from a secure context
 * Notifications are overwhelming produced in tandem with the Push API which is [already restricted to secure contexts](https://w3c.github.io/push-api/#security-and-privacy-considerations). This restriction is only relevant for sites displaying local notifications while they are open in a browser tab
 * Aligning with the requirements of the Push API reduces developer friction and improves platform predictability
 * Chromium already requires local notifications on Android to be requested over a secure context
 * Notifications allow access to privileged system UI, making them a powerful feature

In light of this, we'd like to propose an update to the spec to explicitly require that user agents only make the Notifications API available over secure contexts, and to codify the behaviour of the API when requested from an insecure context. We also welcome suggestions on our proposed behaviour and whether it could be improved.

**Comment by foolip** [comment]
These two things seem like different approaches to me:
* "calls to Notification.requestPermission() and the Notification constructor from an insecure context will act as though the user has denied permission"
* "require that user agents only make the Notifications API available over secure contexts"

I don't really have any stake in the Notifications API Standard or how this should work, but which concrete changes to the spec would you like to see? Per https://github.com/whatwg/meta/blob/master/CONTRIBUTING.md#tests it might make sense to simply write tests first and let the rest follow from that.

**Comment by foolip** [comment]
Ping @dominickng

**Comment by dominickng** [comment]
Sorry for the delay here. Thanks for the advice - we'll follow up with some web-platform-tests and go from there.

**Comment by martinthomson** [comment]
At a minimum, the spec should include `[SecureContext]` on `ServiceWorkerRegistration`.

**Comment by annevk** [comment]
@martinthomson isn't that implied by using "partial interface"? You need it for the NoInterfaceObject/implements construct, but not for "partial interface" as I understand it. We should add it to `NotificationEvent` though.

**Comment by martinthomson** [comment]
To my reading the spec is unclear on this point. It allows [SecureContext] on partial interfaces, but doesn't say what it means to have it omitted. The obvious interpretation is that it is inherited from the main interface, but why then allow it to be added?

**Comment by annevk** [comment]
To add things to the main interface that are restricted. https://heycam.github.io/webidl/#SecureContext backs that up.

**Comment by annevk** [comment]
FWIW, Mozilla is supportive of this change. @dominickng is there anything I can do to help move this forward?

**Comment by dominickng** [comment]
@annevk that's great! I have WPT for this waiting at https://github.com/w3c/web-platform-tests/pull/6596 for a review.

Otherwise I'd appreciate your advice on the best way to codify this requirement in the spec; Chrome's implementation is that calling Notification.requestPermission() returns that permission is denied, and showing a notification over a secure context also acts as if permission is denied. 

I'm guessing the best place is a new line under the "Permissions" section saying that permission can only be granted to secure contexts?

**Comment by annevk** [comment]
I think the cleanest way to do this would be to change the members defined in https://notifications.spec.whatwg.org/#static-members to branch on the secure context check result and return "denied". We don't have to change anything else in principle since they already error if it's not "granted" (of course, existing users would need to be migrated in some way and that's up to UAs, imo).

I guess hiding the interfaces completely is too much of a compatibility risk at this point, so this change seems reasonable to me.

**Comment by dominickng** [comment]
Thanks. I've created https://github.com/whatwg/notifications/pull/121, we can move the discussion to there.

**Comment by annevk** [comment]
Our usual approach is leaving the issue open until the PR is merged (and close it from the commit). Based on that I'm reopening this.

**Comment by johannhof** [comment]
FYI we now are planning to ship this (deny non-secure context permission requests for notifications) in Gecko. The bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1429432 and the intent is here: https://groups.google.com/forum/#!topic/mozilla.dev.platform/FMPrIMGBNtg

**Comment by dominickng** [comment]
@johannhof that's awesome! I've dropped the ball here on getting this standardised (I actually work on a different component of Chrome now), but I should try and find the time to move this forward again now that Gecko is going to ship too.

**Comment by miketaylr** [comment]
So what's left to close out this issue? Fix up https://github.com/web-platform-tests/wpt/pull/6596, write some spec text, according to https://github.com/whatwg/notifications/issues/93#issuecomment-366642469?

@dominickng if you don't object, I can try to push this over the line.

**Comment by dominickng** [comment]
@miketaylr happy for you to take this on - I'm working on a different area of Chrome these days and I'm not actively involved in permissions any more. :)

**Comment by miketaylr** [comment]
Updated the WPT PR @ https://github.com/web-platform-tests/wpt/pull/31495 - I removed the non-top-level-site tests though - that feels like a separate issue.
