### ISSUE TITLE
Strange wording in warning

### ISSUE THREAD

**Issue by foolip** [whatwg/notifications#95]
https://notifications.spec.whatwg.org/#dom-notification-requestpermission

> In designing the platform notifications are the one instance thus far where asking the user upfront makes sense. Specifications for other APIs should not use this pattern and instead employ one of the many more suitable alternatives.

Right around the "are" I'm not sure how to continue parsing. Would suggest a fix but am not sure what was intended :)

**Comment by foolip** [comment]
Looks like this came from https://github.com/whatwg/notifications/pull/36

**Comment by beverloo** [comment]
Thanks! It predates the Bikeshed conversion, so probably has been there for a very long time. I've send a PR to improve the wording.
